// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq5u2CB6-OaFrgqmWjfhIdqgHIwZzTk48',
    appId: '1:621288515186:web:771ec9885574b1cb5484eb',
    messagingSenderId: '621288515186',
    projectId: 'carsigo-9e508',
    authDomain: 'carsigo-9e508.firebaseapp.com',
    storageBucket: 'carsigo-9e508.firebasestorage.app',
    measurementId: 'G-ML0FR24J7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHyBIdsnrFw-VaDmeg3kAA6Dxxo5V_72M',
    appId: '1:621288515186:android:fdf0bfde98a6aa8e5484eb',
    messagingSenderId: '621288515186',
    projectId: 'carsigo-9e508',
    storageBucket: 'carsigo-9e508.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-YA_nvNayuJJ59idi1mRG0kyRr87ZhmA',
    appId: '1:621288515186:ios:627c35a37c65290d5484eb',
    messagingSenderId: '621288515186',
    projectId: 'carsigo-9e508',
    storageBucket: 'carsigo-9e508.firebasestorage.app',
    iosClientId: '621288515186-55s62kui329u023iv62bit52kcoklo36.apps.googleusercontent.com',
    iosBundleId: 'com.example.carsigoMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-YA_nvNayuJJ59idi1mRG0kyRr87ZhmA',
    appId: '1:621288515186:ios:627c35a37c65290d5484eb',
    messagingSenderId: '621288515186',
    projectId: 'carsigo-9e508',
    storageBucket: 'carsigo-9e508.firebasestorage.app',
    iosClientId: '621288515186-55s62kui329u023iv62bit52kcoklo36.apps.googleusercontent.com',
    iosBundleId: 'com.example.carsigoMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq5u2CB6-OaFrgqmWjfhIdqgHIwZzTk48',
    appId: '1:621288515186:web:1d8c328b5a7f71cb5484eb',
    messagingSenderId: '621288515186',
    projectId: 'carsigo-9e508',
    authDomain: 'carsigo-9e508.firebaseapp.com',
    storageBucket: 'carsigo-9e508.firebasestorage.app',
    measurementId: 'G-VCFXQ3WGRM',
  );
}
