name: carsigo_mobile
description: "A new Flutter project for CarSiGo hiperlocal transport."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.5.0
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/sub.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#0a0a0b"
  adaptive_icon_foreground: "assets/sub.png"
